// WARNING:
// This file was generated by the Microsoft DataWarehouse String Resource Tool 1.33.0.0
// from information in SkinCaptions.strings.
// DO NOT MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
// 
namespace Vogue2_IMS.Common
{
	using System;
	using System.Resources;
	using System.Globalization;
	
	
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class SkinCaptions
	{
		
		protected SkinCaptions()
		{
		}
		
		public static CultureInfo Culture
		{
			get
			{
				return Keys.Culture;
			}
			set
			{
				Keys.Culture = value;
			}
		}
		
		public static string Black
		{
			get
			{
				return Keys.GetString(Keys.Black);
			}
		}
		
		public static string Blue
		{
			get
			{
				return Keys.GetString(Keys.Blue);
			}
		}
		
		public static string Caramel
		{
			get
			{
				return Keys.GetString(Keys.Caramel);
			}
		}
		
		public static string DevExpressDarkStyle
		{
			get
			{
				return Keys.GetString(Keys.DevExpressDarkStyle);
			}
		}
		
		public static string DevExpressStyle
		{
			get
			{
				return Keys.GetString(Keys.DevExpressStyle);
			}
		}
		
		public static string iMaginary
		{
			get
			{
				return Keys.GetString(Keys.iMaginary);
			}
		}
		
		public static string Lilian
		{
			get
			{
				return Keys.GetString(Keys.Lilian);
			}
		}
		
		public static string MoneyTwins
		{
			get
			{
				return Keys.GetString(Keys.MoneyTwins);
			}
		}
		
		public static string Office2007Black
		{
			get
			{
				return Keys.GetString(Keys.Office2007Black);
			}
		}
		
		public static string Office2007Blue
		{
			get
			{
				return Keys.GetString(Keys.Office2007Blue);
			}
		}
		
		public static string Office2007Green
		{
			get
			{
				return Keys.GetString(Keys.Office2007Green);
			}
		}
		
		public static string Office2007Pink
		{
			get
			{
				return Keys.GetString(Keys.Office2007Pink);
			}
		}
		
		public static string Office2007Silver
		{
			get
			{
				return Keys.GetString(Keys.Office2007Silver);
			}
		}
		
		public static string Office2010Black
		{
			get
			{
				return Keys.GetString(Keys.Office2010Black);
			}
		}
		
		public static string Office2010Blue
		{
			get
			{
				return Keys.GetString(Keys.Office2010Blue);
			}
		}
		
		public static string Office2010Silver
		{
			get
			{
				return Keys.GetString(Keys.Office2010Silver);
			}
		}
		
		public static string Blueprint
		{
			get
			{
				return Keys.GetString(Keys.Blueprint);
			}
		}
		
		public static string Coffee
		{
			get
			{
				return Keys.GetString(Keys.Coffee);
			}
		}
		
		public static string DarkSide
		{
			get
			{
				return Keys.GetString(Keys.DarkSide);
			}
		}
		
		public static string Darkroom
		{
			get
			{
				return Keys.GetString(Keys.Darkroom);
			}
		}
		
		public static string Foggy
		{
			get
			{
				return Keys.GetString(Keys.Foggy);
			}
		}
		
		public static string GlassOceans
		{
			get
			{
				return Keys.GetString(Keys.GlassOceans);
			}
		}
		
		public static string HighContrast
		{
			get
			{
				return Keys.GetString(Keys.HighContrast);
			}
		}
		
		public static string LiquidSky
		{
			get
			{
				return Keys.GetString(Keys.LiquidSky);
			}
		}
		
		public static string LondonLiquidSky
		{
			get
			{
				return Keys.GetString(Keys.LondonLiquidSky);
			}
		}
		
		public static string McSkin
		{
			get
			{
				return Keys.GetString(Keys.McSkin);
			}
		}
		
		public static string Pumpkin
		{
			get
			{
				return Keys.GetString(Keys.Pumpkin);
			}
		}
		
		public static string Seven
		{
			get
			{
				return Keys.GetString(Keys.Seven);
			}
		}
		
		public static string SevenClassic
		{
			get
			{
				return Keys.GetString(Keys.SevenClassic);
			}
		}
		
		public static string Sharp
		{
			get
			{
				return Keys.GetString(Keys.Sharp);
			}
		}
		
		public static string SharpPlus
		{
			get
			{
				return Keys.GetString(Keys.SharpPlus);
			}
		}
		
		public static string Springtime
		{
			get
			{
				return Keys.GetString(Keys.Springtime);
			}
		}
		
		public static string Stardust
		{
			get
			{
				return Keys.GetString(Keys.Stardust);
			}
		}
		
		public static string Summer
		{
			get
			{
				return Keys.GetString(Keys.Summer);
			}
		}
		
		public static string TheAsphaltWorld
		{
			get
			{
				return Keys.GetString(Keys.TheAsphaltWorld);
			}
		}
		
		public static string Valentine
		{
			get
			{
				return Keys.GetString(Keys.Valentine);
			}
		}
		
		public static string VS2010
		{
			get
			{
				return Keys.GetString(Keys.VS2010);
			}
		}
		
		public static string Whiteprint
		{
			get
			{
				return Keys.GetString(Keys.Whiteprint);
			}
		}
		
		public static string XmasBlue
		{
			get
			{
				return Keys.GetString(Keys.XmasBlue);
			}
		}
		
		[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		public class Keys
		{
			
			static ResourceManager resourceManager = new ResourceManager(typeof(SkinCaptions).FullName, typeof(SkinCaptions).Module.Assembly);
			
			static CultureInfo _culture = null;
			
			public const string Black = "Black";
			
			public const string Blue = "Blue";
			
			public const string Caramel = "Caramel";
			
			public const string DevExpressDarkStyle = "DevExpressDarkStyle";
			
			public const string DevExpressStyle = "DevExpressStyle";
			
			public const string iMaginary = "iMaginary";
			
			public const string Lilian = "Lilian";
			
			public const string MoneyTwins = "MoneyTwins";
			
			public const string Office2007Black = "Office2007Black";
			
			public const string Office2007Blue = "Office2007Blue";
			
			public const string Office2007Green = "Office2007Green";
			
			public const string Office2007Pink = "Office2007Pink";
			
			public const string Office2007Silver = "Office2007Silver";
			
			public const string Office2010Black = "Office2010Black";
			
			public const string Office2010Blue = "Office2010Blue";
			
			public const string Office2010Silver = "Office2010Silver";
			
			public const string Blueprint = "Blueprint";
			
			public const string Coffee = "Coffee";
			
			public const string DarkSide = "DarkSide";
			
			public const string Darkroom = "Darkroom";
			
			public const string Foggy = "Foggy";
			
			public const string GlassOceans = "GlassOceans";
			
			public const string HighContrast = "HighContrast";
			
			public const string LiquidSky = "LiquidSky";
			
			public const string LondonLiquidSky = "LondonLiquidSky";
			
			public const string McSkin = "McSkin";
			
			public const string Pumpkin = "Pumpkin";
			
			public const string Seven = "Seven";
			
			public const string SevenClassic = "SevenClassic";
			
			public const string Sharp = "Sharp";
			
			public const string SharpPlus = "SharpPlus";
			
			public const string Springtime = "Springtime";
			
			public const string Stardust = "Stardust";
			
			public const string Summer = "Summer";
			
			public const string TheAsphaltWorld = "TheAsphaltWorld";
			
			public const string Valentine = "Valentine";
			
			public const string VS2010 = "VS2010";
			
			public const string Whiteprint = "Whiteprint";
			
			public const string XmasBlue = "XmasBlue";
			
			private Keys()
			{
			}
			
			public static CultureInfo Culture
			{
				get
				{
					return _culture;
				}
				set
				{
					_culture = value;
				}
			}
			
			public static string GetString(string key)
			{
				return resourceManager.GetString(key, _culture);
			}
		}
	}
}
