using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.XtraPrinting.Localization;
using System.IO;

namespace Pst.DExpress.Localization.ControlLocalization
{
    public class XtraPreviewLocaizer : PreviewLocalizer
    {
        public override string Language
        {
            get
            {
                return " 简体中文 ";
            }
        }

        public override string GetLocalizedString(PreviewStringId id)
        {
            switch (id)
            {
                #region know id

                case PreviewStringId.EmptyString: return @"  ";
                case PreviewStringId.PPF_Preview_Caption: return @"  ";
                case PreviewStringId.TB_CustomizeBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_PrintBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_PrintDirectBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_PageSetupBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_MagnifierBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_ZoomInBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_ZoomOutBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_ZoomBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_SearchBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_FirstPageBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_PreviousPageBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_NextPageBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_LastPageBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_MultiplePagesBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_BackGroundBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_ClosePreviewBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_EditPageHFBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_HandToolBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_ExportBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_SendBtn_ToolTip: return @"  ";
                case PreviewStringId.TB_DocMap_ToolTip: return @"  ";
                case PreviewStringId.TB_Watermark_ToolTip: return @"  ";
                case PreviewStringId.barExport_PDF_Document: return @"  ";
                case PreviewStringId.barExport_Text_Document: return @"  ";
                case PreviewStringId.barExport_CSV_Document: return @"  ";
                case PreviewStringId.barExport_MHT_Document: return @"  ";
                case PreviewStringId.barExport_Excel_Document: return @"  ";
                case PreviewStringId.barExport_RichTextDocument: return @"  ";
                case PreviewStringId.barExport_HTMLDocument: return @"  ";
                case PreviewStringId.barExport_BMP: return @"  ";
                case PreviewStringId.barExport_GIF: return @"  ";
                case PreviewStringId.barExport_JPEG: return @"  ";
                case PreviewStringId.barExport_PNG: return @"  ";
                case PreviewStringId.barExport_TIFF: return @"  ";
                case PreviewStringId.barExport_EMF: return @"  ";
                case PreviewStringId.SaveDlg_FilterEmf: return @" EMF Windows图元文件 ";
                case PreviewStringId.barExport_WMF: return @"  ";
                case PreviewStringId.SB_PageInfo_OF: return @"  ";
                case PreviewStringId.PCE_PageContentEditor_Caption: return @"  ";
                case PreviewStringId.PCE_PageNumber_ToolTip: return @"  ";
                case PreviewStringId.PCE_PageOfPages_ToolTip: return @"  ";
                case PreviewStringId.PCE_DatePrinted_ToolTip: return @"  ";
                case PreviewStringId.PCE_TimePrinted_ToolTip: return @"  ";
                case PreviewStringId.PCE_UserName_ToolTip: return @"  ";
                case PreviewStringId.PCE_Image_ToolTip: return @"  ";
                case PreviewStringId.PCE_FontButton: return @"  ";
                case PreviewStringId.PCE_FooterLabel: return @"  ";
                case PreviewStringId.PCE_HeaderLabel: return @"  ";
                case PreviewStringId.PCE_AlignTops_ToolTip: return @"  ";
                case PreviewStringId.PCE_AlignMiddles_ToolTip: return @"  ";
                case PreviewStringId.PCE_AlignBottoms_ToolTip: return @"  ";
                case PreviewStringId.MPE_PagesLabel: return @"  ";
                case PreviewStringId.Msg_UnavailableNetPrinter: return @" 网络打印机不可用. ";
                case PreviewStringId.Msg_WrongPrinting: return @" 打印文档时发生错误. ";
                case PreviewStringId.Msg_IncorrectZoomFactor: return @" 编号必须是{ 0 }和{ 1 }. ";
                case PreviewStringId.Msg_InvalidMeasurement: return @" 无效尺寸. ";
                case PreviewStringId.Msg_CannotAccessFile: return @" 进程无法访问被占用的文件“{ 0 }”. ";
                case PreviewStringId.Msg_FileReadOnly: return @" “{ 0 }”为只读文件，尝试使用其它文件名. ";
                case PreviewStringId.Msg_OpenFileQuestion: return @" 是否打开此文件? ";
                case PreviewStringId.Msg_OpenFileQuestionCaption: return @" 导出 ";
                case PreviewStringId.Msg_CantFitBarcodeToControlBounds: return @" 控件边距太小 ";
                case PreviewStringId.Msg_InvalidBarcodeText: return @" 内容包含无效字符 ";
                case PreviewStringId.Msg_InvalidBarcodeTextFormat: return @" 无效的文本格式 ";
                case PreviewStringId.Msg_InvalidBarcodeData: return @" 二进制数据的长度不能超过1033字节. ";
                case PreviewStringId.Msg_SearchDialogFinishedSearching: return @" 文档搜索完成 ";
                case PreviewStringId.Msg_SearchDialogTotalFound: return @" 共找到:  ";
                case PreviewStringId.Msg_SearchDialogReady: return @" 准备好 ";
                case PreviewStringId.Msg_NoDifferentFilesInStream: return @" 文件不能被导出到此文件格式。使用单文件或单文件页模式代替. ";
                case PreviewStringId.Msg_BigFileToCreate: return @" 文件大小超出限制. 请尝试删减页数或者分解文件. ";
                case PreviewStringId.Msg_BigFileToCreateJPEG: return @" 文件大小超出Image文件限制. 请选择其它图片格式导出. ";
                case PreviewStringId.Msg_BigBitmapToCreate: return @" 文件大小超出Bitmap文件限制. 请降低文件分辨率或者选择其它格式导出. ";
                case PreviewStringId.Msg_XlsMoreThanMaxRows: return @" 文件大小超出Xls文件行数限制, 行数超出了 65,536 .请尝试导出为xlsx或者其它格式. ";
                case PreviewStringId.Msg_XlsMoreThanMaxColumns: return @" 文件大小超出Xls文件列数限制, 列数超出了 256 .请尝试导出为xlsx或者其它格式. ";
                case PreviewStringId.Msg_XlsxMoreThanMaxRows: return @" 文件大小超出Xlsx文件行数限制, 行数超出了 65,536 1,048,576.请调整行数再导出. ";
                case PreviewStringId.Msg_XlsxMoreThanMaxColumns: return @" 文件大小超出Xlsx文件列数限制, 行数超出了 16,384 .请调整列数再导出. ";
                case PreviewStringId.Msg_FileDosntHavePrnxExtention: return @" 指点定文件没有 PRNX 扩展. 是否继续? ";
                case PreviewStringId.Msg_FileDosntContainValidXml: return @" 指定文件没有包含有效的XML数据格式. 已停止加载. ";
                case PreviewStringId.Msg_GoToNonExistentPage: return @" 未找到页码 {0}. ";
                case PreviewStringId.Msg_Caption: return @" 打印中 ";
                case PreviewStringId.Msg_PathTooLong: return @" 路径太长.
请缩减长度. ";
                case PreviewStringId.Msg_CannotLoadDocument: return @" 指定文件加载失败： 不是有效的XML格式或者数据量超出限制. ";
                case PreviewStringId.Shapes_Rectangle: return @" 矩形 ";
                case PreviewStringId.Shapes_Ellipse: return @" 椭圆 ";
                case PreviewStringId.Shapes_Arrow: return @" 箭头 ";
                case PreviewStringId.Shapes_TopArrow: return @" 向上箭头 ";
                case PreviewStringId.Shapes_BottomArrow: return @" 向下 箭头 ";
                case PreviewStringId.Shapes_LeftArrow: return @" 向左 箭头 ";
                case PreviewStringId.Shapes_RightArrow: return @" 向右 箭头 ";
                case PreviewStringId.Shapes_Polygon: return @" 多边型 ";
                case PreviewStringId.Shapes_Triangle: return @" 三角型 ";
                case PreviewStringId.Shapes_Square: return @" 广角 ";
                case PreviewStringId.Shapes_Pentagon: return @" 五角型 ";
                case PreviewStringId.Shapes_Hexagon: return @" 六角型 ";
                case PreviewStringId.Shapes_Octagon: return @" 八角型 ";
                case PreviewStringId.Shapes_Star: return @" 星型 ";
                case PreviewStringId.Shapes_ThreePointStar: return @" 三角星 ";
                case PreviewStringId.Shapes_FourPointStar: return @" 四角星 ";
                case PreviewStringId.Shapes_FivePointStar: return @" 五角星 ";
                case PreviewStringId.Shapes_SixPointStar: return @" 六角星 ";
                case PreviewStringId.Shapes_EightPointStar: return @" 八角星 ";
                case PreviewStringId.Shapes_Line: return @" 直线 ";
                case PreviewStringId.Shapes_SlantLine: return @" 斜线 ";
                case PreviewStringId.Shapes_BackslantLine: return @" 左侧线 ";
                case PreviewStringId.Shapes_HorizontalLine: return @" 水平线 ";
                case PreviewStringId.Shapes_VerticalLine: return @" 垂直线 ";
                case PreviewStringId.Shapes_Cross: return @" 交叉 ";
                case PreviewStringId.Shapes_Brace: return @" 支撑 ";
                case PreviewStringId.Shapes_Bracket: return @" 支架 ";
                case PreviewStringId.Page_Scroll: return @"  ";
                case PreviewStringId.dlgSaveAs: return @"  ";
                case PreviewStringId.SaveDlg_FilterXlsx: return @" XLSX 文档 ";
                case PreviewStringId.SaveDlg_FilterXps: return @" XPS 文档 ";
                case PreviewStringId.dlgSendFrom: return @"  ";
                case PreviewStringId.ExportOption_PdfChangingPermissions_None: return @" 空 ";
                case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Caption: return @" 文档访问密码 ";
                case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Note: return @" 请确认并记录下文档访问密码. 以后访问文档需要此密码. ";
                case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Name: return @" 文档打开密码: ";
                case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Caption: return @" 确认权限密码 ";
                case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Note: return @" 请确认并记录下权限密码. 修改此项设置时需要此密码 ";
                case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Name: return @" &权限密码: ";
                case PreviewStringId.ExportOption_ConfirmationDoesNotMatchForm_Msg: return @" 确认密码不匹配,请重新输入. ";
                case PreviewStringId.ExportOption_XlsUseNativeFormat: return @" 导出格式化结果 ";
                case PreviewStringId.ExportOption_NativeFormatCompressed: return @" 压缩 ";
                case PreviewStringId.ExportOption_XpsPageRange: return @" 页面范围: ";
                case PreviewStringId.ExportOption_XpsCompression: return @" 压缩: ";
                case PreviewStringId.ExportOption_XpsCompression_NotCompressed: return @" 不压缩 ";
                case PreviewStringId.ExportOption_XpsCompression_Normal: return @" 正常 ";
                case PreviewStringId.ExportOption_XpsCompression_Maximum: return @" 最大 ";
                case PreviewStringId.ExportOption_XpsCompression_Fast: return @" 快速 ";
                case PreviewStringId.ExportOption_XpsCompression_SuperFast: return @" 极快 ";
                case PreviewStringId.ExportOption_XpsDocumentCreator: return @" 作者: ";
                case PreviewStringId.ExportOption_XpsDocumentCategory: return @" 类别: ";
                case PreviewStringId.ExportOption_XpsDocumentTitle: return @" 标题: ";
                case PreviewStringId.ExportOption_XpsDocumentSubject: return @" 主题: ";
                case PreviewStringId.ExportOption_XpsDocumentKeywords: return @" 关键字: ";
                case PreviewStringId.ExportOption_XpsDocumentVersion: return @" 版本号: ";
                case PreviewStringId.ExportOption_XpsDocumentDescription: return @" 描述: ";
                case PreviewStringId.FolderBrowseDlg_ExportDirectory: return @" 选择保存地址: ";
                case PreviewStringId.ExportOptionsForm_CaptionNativeOptions: return @" 本地格式化选项 ";
                case PreviewStringId.ExportOptionsForm_CaptionXps: return @" XPS 导出选项 ";
                case PreviewStringId.RibbonPreview_PageText: return @" 打印预览 ";
                case PreviewStringId.RibbonPreview_PageGroup_Print: return @" 打印 ";
                case PreviewStringId.RibbonPreview_PageGroup_PageSetup: return @" 页面设置 ";
                case PreviewStringId.RibbonPreview_PageGroup_Navigation: return @" 导航 ";
                case PreviewStringId.RibbonPreview_PageGroup_Zoom: return @" 变焦 ";
                case PreviewStringId.RibbonPreview_PageGroup_Background: return @" 页面背景 ";
                case PreviewStringId.RibbonPreview_PageGroup_Export: return @" 导出 ";
                case PreviewStringId.RibbonPreview_PageGroup_Document: return @" 文档 ";
                case PreviewStringId.RibbonPreview_DocumentMap_Caption: return @" 书签 ";
                case PreviewStringId.RibbonPreview_Parameters_Caption: return @" 参数 ";
                case PreviewStringId.RibbonPreview_Find_Caption: return @" 查找 ";
                case PreviewStringId.RibbonPreview_Pointer_Caption: return @" 指针 ";
                case PreviewStringId.RibbonPreview_HandTool_Caption: return @" 抓手工具 ";
                case PreviewStringId.RibbonPreview_Customize_Caption: return @" 选项 ";
                case PreviewStringId.RibbonPreview_Print_Caption: return @" 打印 ";
                case PreviewStringId.RibbonPreview_PrintDirect_Caption: return @" 快速打印 ";
                case PreviewStringId.RibbonPreview_PageSetup_Caption: return @" 自定义边距... ";
                case PreviewStringId.RibbonPreview_EditPageHF_Caption: return @" 页头/页尾 ";
                case PreviewStringId.RibbonPreview_Magnifier_Caption: return @" 放大镜 ";
                case PreviewStringId.RibbonPreview_ZoomOut_Caption: return @" 缩小 ";
                case PreviewStringId.RibbonPreview_ZoomExact_Caption: return @" 精确: ";
                case PreviewStringId.RibbonPreview_ZoomIn_Caption: return @" 放大 ";
                case PreviewStringId.RibbonPreview_ShowFirstPage_Caption: return @" 第一页 ";
                case PreviewStringId.RibbonPreview_ShowPrevPage_Caption: return @" 上一页 ";
                case PreviewStringId.RibbonPreview_ShowNextPage_Caption: return @" 下一页  ";
                case PreviewStringId.RibbonPreview_ShowLastPage_Caption: return @" 最后一页  ";
                case PreviewStringId.RibbonPreview_MultiplePages_Caption: return @" 多页 ";
                case PreviewStringId.RibbonPreview_FillBackground_Caption: return @" 页面背景色 ";
                case PreviewStringId.RibbonPreview_Watermark_Caption: return @" 水印 ";
                case PreviewStringId.RibbonPreview_ExportFile_Caption: return @" 导出为 ";
                case PreviewStringId.RibbonPreview_SendFile_Caption: return @" 发送为 ";
                case PreviewStringId.RibbonPreview_ClosePreview_Caption: return @" 关闭打印预览 ";
                case PreviewStringId.RibbonPreview_Scale_Caption: return @" 范围 ";
                case PreviewStringId.RibbonPreview_PageOrientation_Caption: return @" 定位 ";
                case PreviewStringId.RibbonPreview_PaperSize_Caption: return @" 大小 ";
                case PreviewStringId.RibbonPreview_PageMargins_Caption: return @" 页边距 ";
                case PreviewStringId.RibbonPreview_Zoom_Caption: return @" 变焦 ";
                case PreviewStringId.RibbonPreview_DocumentMap_STipTitle: return @" 文档结构图 ";
                case PreviewStringId.RibbonPreview_Parameters_STipTitle: return @" 参数 ";
                case PreviewStringId.RibbonPreview_Find_STipTitle: return @" 查找 ";
                case PreviewStringId.RibbonPreview_Pointer_STipTitle: return @" 鼠标指针 ";
                case PreviewStringId.RibbonPreview_HandTool_STipTitle: return @" 抓手工具 ";
                case PreviewStringId.RibbonPreview_Customize_STipTitle: return @" 选项 ";
                case PreviewStringId.RibbonPreview_Print_STipTitle: return @" 打印 (Ctrl+P) ";
                case PreviewStringId.RibbonPreview_PrintDirect_STipTitle: return @" 快速打印 ";
                case PreviewStringId.RibbonPreview_PageSetup_STipTitle: return @" 页面设置 ";
                case PreviewStringId.RibbonPreview_EditPageHF_STipTitle: return @" 页头与页尾 ";
                case PreviewStringId.RibbonPreview_Magnifier_STipTitle: return @" 放大镜 ";
                case PreviewStringId.RibbonPreview_ZoomOut_STipTitle: return @" 缩小 ";
                case PreviewStringId.RibbonPreview_ZoomIn_STipTitle: return @" 放大 ";
                case PreviewStringId.RibbonPreview_ShowFirstPage_STipTitle: return @" 第一页 (Ctrl+Home) ";
                case PreviewStringId.RibbonPreview_ShowPrevPage_STipTitle: return @" 上一页 (PageUp) ";
                case PreviewStringId.RibbonPreview_ShowNextPage_STipTitle: return @" 下一页 (PageDown) ";
                case PreviewStringId.RibbonPreview_ShowLastPage_STipTitle: return @" 最后一页 (Ctrl+End) ";
                case PreviewStringId.RibbonPreview_MultiplePages_STipTitle: return @" 查看多页 ";
                case PreviewStringId.RibbonPreview_FillBackground_STipTitle: return @" 背景色 ";
                case PreviewStringId.RibbonPreview_Watermark_STipTitle: return @" 水印 ";
                case PreviewStringId.RibbonPreview_ExportFile_STipTitle: return @" 导出到... ";
                case PreviewStringId.RibbonPreview_SendFile_STipTitle: return @" 发送到... ";
                case PreviewStringId.RibbonPreview_ClosePreview_STipTitle: return @" 关闭打印预览 ";
                case PreviewStringId.RibbonPreview_Scale_STipTitle: return @" 范围 ";
                case PreviewStringId.RibbonPreview_PageOrientation_STipTitle: return @" 页面方向 ";
                case PreviewStringId.RibbonPreview_PaperSize_STipTitle: return @" 页面大小 ";
                case PreviewStringId.RibbonPreview_PageMargins_STipTitle: return @" 页面边距 ";
                case PreviewStringId.RibbonPreview_Zoom_STipTitle: return @" 变焦 ";
                case PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipTitle: return @" 页面设置 ";
                case PreviewStringId.RibbonPreview_Save_STipTitle: return @" 保存 (Ctrl + S) ";
                case PreviewStringId.RibbonPreview_Open_STipTitle: return @" 打开 (Ctrl + O) ";
                case PreviewStringId.RibbonPreview_DocumentMap_STipContent: return @" 打开一个可浏览的文档结构图. ";
                case PreviewStringId.RibbonPreview_Parameters_STipContent: return @" 打开报表参数输入窗口. ";
                case PreviewStringId.RibbonPreview_Find_STipContent: return @" 显示查找对话框，查询指定内容. ";
                case PreviewStringId.RibbonPreview_Pointer_STipContent: return @" 显示鼠标指针. ";
                case PreviewStringId.RibbonPreview_HandTool_STipContent: return @" 使用拍手工具拖动页面. ";
                case PreviewStringId.RibbonPreview_Customize_STipContent: return @" 打开“打印选项”对话框，用于调整打印选项. ";
                case PreviewStringId.RibbonPreview_Print_STipContent: return @" 选择打印机、打印份数和打印选项等. ";
                case PreviewStringId.RibbonPreview_PrintDirect_STipContent: return @" 直接使用默认打印机. ";
                case PreviewStringId.RibbonPreview_PageSetup_STipContent: return @" 显示“页面设置”对话框. ";
                case PreviewStringId.RibbonPreview_EditPageHF_STipContent: return @" 编辑文档的页尾页角. ";
                case PreviewStringId.RibbonPreview_Magnifier_STipContent: return @" 使用放大镜工具.

点击一次页面整页显示, 再点击一次页面100%大小显示. ";
                case PreviewStringId.RibbonPreview_ZoomOut_STipContent: return @" 缩小页面尺寸. ";
                case PreviewStringId.RibbonPreview_ZoomIn_STipContent: return @" 放大页面尺寸. ";
                case PreviewStringId.RibbonPreview_ShowFirstPage_STipContent: return @" 定位到第一页. ";
                case PreviewStringId.RibbonPreview_ShowPrevPage_STipContent: return @" 定位到上一页. ";
                case PreviewStringId.RibbonPreview_ShowNextPage_STipContent: return @" 定位到下一页. ";
                case PreviewStringId.RibbonPreview_ShowLastPage_STipContent: return @" 定位到最后一页. ";
                case PreviewStringId.RibbonPreview_MultiplePages_STipContent: return @" 选择预览窗口的页面布局. ";
                case PreviewStringId.RibbonPreview_FillBackground_STipContent: return @" 选择页面背景色或背景图片. ";
                case PreviewStringId.RibbonPreview_Watermark_STipContent: return @" 插入/替换页面中的文本或者图像.

通常表示一个被特殊关注的文件. ";
                case PreviewStringId.RibbonPreview_ExportFile_STipContent: return @" 导出指定格式的文件并保存. ";
                case PreviewStringId.RibbonPreview_SendFile_STipContent: return @" 导出指定格式的文件发送. ";
                case PreviewStringId.RibbonPreview_ClosePreview_STipContent: return @" 关闭打印预览. ";
                case PreviewStringId.RibbonPreview_Scale_STipContent: return @" 调整打印文档的实际大小比例. ";
                case PreviewStringId.RibbonPreview_PageOrientation_STipContent: return @" 调整页面横(纵)向布局. ";
                case PreviewStringId.RibbonPreview_PaperSize_STipContent: return @" 选择纸张大小. ";
                case PreviewStringId.RibbonPreview_PageMargins_STipContent: return @" 选择整个文件边距大小.

单击“自定义边距”实现自定义. ";
                case PreviewStringId.RibbonPreview_Zoom_STipContent: return @" 调整文档预览缩放. ";
                case PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipContent: return @" 显示“页面设置”对话框. ";
                case PreviewStringId.RibbonPreview_Save_STipContent: return @" 保存文档. ";
                case PreviewStringId.RibbonPreview_Open_STipContent: return @" 打开文档. ";
                case PreviewStringId.RibbonPreview_ExportPdf_Caption: return @" PDF 文件 ";
                case PreviewStringId.RibbonPreview_ExportHtm_Caption: return @" HTML 文件 ";
                case PreviewStringId.RibbonPreview_ExportMht_Caption: return @" MHT 文件 ";
                case PreviewStringId.RibbonPreview_ExportRtf_Caption: return @" RTF 文件 ";
                case PreviewStringId.RibbonPreview_ExportXls_Caption: return @" XLS 文件 ";
                case PreviewStringId.RibbonPreview_ExportXlsx_Caption: return @" XLSX 文件 ";
                case PreviewStringId.RibbonPreview_ExportCsv_Caption: return @" CSV 文件 ";
                case PreviewStringId.RibbonPreview_ExportTxt_Caption: return @" Text 文件 ";
                case PreviewStringId.RibbonPreview_ExportGraphic_Caption: return @" Image 文件 ";
                case PreviewStringId.RibbonPreview_ExportXps_Caption: return @" XPS 文件 ";
                case PreviewStringId.RibbonPreview_SendPdf_Caption: return @" PDF 文件 ";
                case PreviewStringId.RibbonPreview_SendMht_Caption: return @" MHT 文件 ";
                case PreviewStringId.RibbonPreview_SendRtf_Caption: return @" RTF 文件 ";
                case PreviewStringId.RibbonPreview_SendXls_Caption: return @" XLS 文件 ";
                case PreviewStringId.RibbonPreview_SendXlsx_Caption: return @" XLSX 文件 ";
                case PreviewStringId.RibbonPreview_SendCsv_Caption: return @" CSV 文件 ";
                case PreviewStringId.RibbonPreview_SendTxt_Caption: return @" Text 文件 ";
                case PreviewStringId.RibbonPreview_SendGraphic_Caption: return @" Image 文件 ";
                case PreviewStringId.RibbonPreview_SendXps_Caption: return @" XPS 文件 ";
                case PreviewStringId.RibbonPreview_ExportPdf_Description: return @" 便携式文本 ";
                case PreviewStringId.RibbonPreview_ExportHtm_Description: return @" 网页 ";
                case PreviewStringId.RibbonPreview_ExportTxt_Description: return @" 纯文本 ";
                case PreviewStringId.RibbonPreview_ExportCsv_Description: return @" 以逗号分隔的文本 ";
                case PreviewStringId.RibbonPreview_ExportMht_Description: return @" 单个网页文本 ";
                case PreviewStringId.RibbonPreview_ExportXls_Description: return @"  Excel 2000-2003 ";
                case PreviewStringId.RibbonPreview_ExportXlsx_Description: return @"  Excel 2007  ";
                case PreviewStringId.RibbonPreview_ExportRtf_Description: return @" 格式化文本 ";
                case PreviewStringId.RibbonPreview_ExportGraphic_Description: return @" BMP, GIF, JPEG, PNG, TIFF, EMF, WMF ";
                case PreviewStringId.RibbonPreview_ExportXps_Description: return @" XPS ";
                case PreviewStringId.RibbonPreview_SendPdf_Description: return @" 便携式文档 ";
                case PreviewStringId.RibbonPreview_SendTxt_Description: return @" 纯文本 ";
                case PreviewStringId.RibbonPreview_SendCsv_Description: return @" 以逗号分隔的文本 ";
                case PreviewStringId.RibbonPreview_SendMht_Description: return @" 单个网页文本 ";
                case PreviewStringId.RibbonPreview_SendXls_Description: return @"  Excel 2000-2003  ";
                case PreviewStringId.RibbonPreview_SendXlsx_Description: return @" Excel 2007  ";
                case PreviewStringId.RibbonPreview_SendRtf_Description: return @" 格式化文本 ";
                case PreviewStringId.RibbonPreview_SendGraphic_Description: return @" BMP, GIF, JPEG, PNG, TIFF, EMF, WMF ";
                case PreviewStringId.RibbonPreview_SendXps_Description: return @" XPS ";
                case PreviewStringId.RibbonPreview_ExportPdf_STipTitle: return @" 导出为 PDF ";
                case PreviewStringId.RibbonPreview_ExportHtm_STipTitle: return @" 导出为 HTML ";
                case PreviewStringId.RibbonPreview_ExportTxt_STipTitle: return @" 导出为 Text ";
                case PreviewStringId.RibbonPreview_ExportCsv_STipTitle: return @" 导出为 CSV ";
                case PreviewStringId.RibbonPreview_ExportMht_STipTitle: return @" 导出为 MHT ";
                case PreviewStringId.RibbonPreview_ExportXls_STipTitle: return @" 导出为 XLS ";
                case PreviewStringId.RibbonPreview_ExportXlsx_STipTitle: return @" 导出为 XLSX ";
                case PreviewStringId.RibbonPreview_ExportRtf_STipTitle: return @" 导出为 RTF ";
                case PreviewStringId.RibbonPreview_ExportGraphic_STipTitle: return @" 导出为 Image ";
                case PreviewStringId.RibbonPreview_SendPdf_STipTitle: return @" 发送 PDF ";
                case PreviewStringId.RibbonPreview_SendTxt_STipTitle: return @" 发送 Text ";
                case PreviewStringId.RibbonPreview_SendCsv_STipTitle: return @" 发送 CSV ";
                case PreviewStringId.RibbonPreview_SendMht_STipTitle: return @" 发送 MHT ";
                case PreviewStringId.RibbonPreview_SendXls_STipTitle: return @" 发送 XLS ";
                case PreviewStringId.RibbonPreview_SendXlsx_STipTitle: return @" 发送 XLSX ";
                case PreviewStringId.RibbonPreview_SendRtf_STipTitle: return @" 发送 RTF ";
                case PreviewStringId.RibbonPreview_SendGraphic_STipTitle: return @" 发送 Image ";
                case PreviewStringId.RibbonPreview_ExportPdf_STipContent: return @" 导出 PDF 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportHtm_STipContent: return @" 导出 HTML 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportTxt_STipContent: return @" 导出 Text 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportCsv_STipContent: return @" 导出 CSV 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportMht_STipContent: return @" 导出 MHT 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportXls_STipContent: return @" 导出 XLS 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportXlsx_STipContent: return @" 导出 XLSX 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportRtf_STipContent: return @" 导出 RTF 到硬盘. ";
                case PreviewStringId.RibbonPreview_ExportGraphic_STipContent: return @" 导出 Image 到硬盘. ";
                case PreviewStringId.RibbonPreview_SendPdf_STipContent: return @" 导出 PDF 并发送. ";
                case PreviewStringId.RibbonPreview_SendTxt_STipContent: return @" 导出 Text 并发送. ";
                case PreviewStringId.RibbonPreview_SendCsv_STipContent: return @" 导出 CSV 并发送. ";
                case PreviewStringId.RibbonPreview_SendMht_STipContent: return @" 导出 MHT 并发送. ";
                case PreviewStringId.RibbonPreview_SendXls_STipContent: return @" 导出 XLS 并发送. ";
                case PreviewStringId.RibbonPreview_SendXlsx_STipContent: return @" 导出 XLSX 并发送. ";
                case PreviewStringId.RibbonPreview_SendRtf_STipContent: return @" 导出 RTF 并发送. ";
                case PreviewStringId.RibbonPreview_SendGraphic_STipContent: return @" 导出 Image 并发送. ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Caption: return @" 标准 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Caption: return @" 适应 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Caption: return @" 正常 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Caption: return @" 精确 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Caption: return @" 中等 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Caption: return @" 模糊 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Description: return @"  ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Description: return @"  ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Description: return @" 普通 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Description: return @" 精确 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Description: return @" 中等 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Description: return @" 模糊 ";
                case PreviewStringId.RibbonPreview_GalleryItem_PageMargins_Description: return @" 上:		{0}		下:		{1}
左:		 {2}		右:		   {3} ";
                case PreviewStringId.RibbonPreview_GalleryItem_PaperSize_Description: return @" {0} x {1} ";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_DocumentOpenPassword: return @" 文档访问密码 ";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_Permissions: return @" 权限 ";
                case PreviewStringId.ParametersRequest_Submit: return @" 提交 ";
                case PreviewStringId.ParametersRequest_Reset: return @" 重置 ";
                case PreviewStringId.ParametersRequest_Caption: return @" 参数 ";


                case PreviewStringId.ExportOption_PdfPrintingPermissions_None: return " 空 ";
                case PreviewStringId.ExportOption_PdfPrintingPermissions_LowResolution: return " 低分辨率 (150 dpi) ";
                case PreviewStringId.ExportOption_PdfPrintingPermissions_HighResolution: return " 高分辨率 ";
                case PreviewStringId.ExportOption_PdfChangingPermissions_InsertingDeletingRotating: return " 插入、删除和旋转页面 ";
                case PreviewStringId.ExportOption_PdfChangingPermissions_FillingSigning: return " 填写表单字段并签署现有签名字段 ";
                case PreviewStringId.ExportOption_PdfChangingPermissions_CommentingFillingSigning: return " 评论、填写表单字段和签署现有签名字段 ";
                case PreviewStringId.ExportOption_PdfChangingPermissions_AnyExceptExtractingPages: return " 除选择页外 ";

                case PreviewStringId.Button_Apply: return " 应用 ";
                case PreviewStringId.Button_Cancel: return " 取消 ";
                case PreviewStringId.Button_Help: return " 帮助 ";
                case PreviewStringId.Button_Ok: return " 确定 ";
                case PreviewStringId.EMail_From: return "From";
                case PreviewStringId.Margin_BottomMargin: return " 下边界 ";
                case PreviewStringId.Margin_Inch: return " 英寸 ";
                case PreviewStringId.Margin_LeftMargin: return " 左边界 ";
                case PreviewStringId.Margin_Millimeter: return " 毫米 ";
                case PreviewStringId.Margin_RightMargin: return " 右边界 ";
                case PreviewStringId.Margin_TopMargin: return " 上边界 ";
                case PreviewStringId.MenuItem_BackgrColor: return " 颜色 (&C) ";
                case PreviewStringId.MenuItem_Background: return " 背景 (&B)";
                case PreviewStringId.MenuItem_CsvDocument: return "CSV 文件 ";
                case PreviewStringId.MenuItem_Exit: return " 退出 (&X)";
                case PreviewStringId.MenuItem_Export: return " 导出 (&E)";
                case PreviewStringId.MenuItem_File: return " 文件 (&F)";
                case PreviewStringId.MenuItem_GraphicDocument: return " 图片文件 ";
                case PreviewStringId.MenuItem_HtmDocument: return "HTML 文件 ";
                case PreviewStringId.MenuItem_MhtDocument: return "MHT 文件 ";
                case PreviewStringId.MenuItem_PageSetup: return " 页面设置 (&U)";
                case PreviewStringId.MenuItem_PdfDocument: return "PDF 文件 ";
                case PreviewStringId.MenuItem_Print: return " 打印 (&P) ";
                case PreviewStringId.MenuItem_PrintDirect: return " 直接打印 (&R)";
                case PreviewStringId.MenuItem_RtfDocument: return "RTF 文件 ";
                case PreviewStringId.MenuItem_Send: return " 发送 (&D)";
                case PreviewStringId.MenuItem_TxtDocument: return "TXT 文件 ";
                case PreviewStringId.MenuItem_View: return " 视图 (&V)";
                case PreviewStringId.MenuItem_ViewStatusbar: return " 状态栏 (&S)";
                case PreviewStringId.MenuItem_ViewToolbar: return " 工具栏 (&T)";
                case PreviewStringId.MenuItem_Watermark: return " 水印 (&W) ";
                case PreviewStringId.MenuItem_XlsDocument: return "XLS 文件 ";
                case PreviewStringId.MPForm_Lbl_Pages: return " 页 ";
                case PreviewStringId.Msg_CreatingDocument: return " 正在生成文件 ";
                case PreviewStringId.Msg_CustomDrawWarning: return " 警告 !";
                case PreviewStringId.Msg_EmptyDocument: return " 此文件没有页面 .";
                case PreviewStringId.Msg_FontInvalidNumber: return " 字体大小不能为 0 或负数 ";
                case PreviewStringId.Msg_IncorrectPageRange: return " 设置的页边界不正确 ";
                case PreviewStringId.Msg_NeedPrinter: return " 没有安装打印机 .";
                case PreviewStringId.Msg_NotSupportedFont: return " 这种字体不被支持 ";
                case PreviewStringId.Msg_PageMarginsWarning: return " 一个或以上的边界超出了打印范围 . 是否继续？ ";
                case PreviewStringId.Msg_WrongPageSettings: return " 打印机不支持所选的纸张大小 .  是否继续打印？ ";
                case PreviewStringId.Msg_WrongPrinter: return " 无效的打印机名称 . 请检查打印机的设置是否正确 .";
                case PreviewStringId.PageInfo_PageDate: return "[打印日期]";
                case PreviewStringId.PageInfo_PageNumber: return "[页 #]";
                case PreviewStringId.PageInfo_PageNumberOfTotal: return "[页 # / 页 #]";
                case PreviewStringId.PageInfo_PageTime: return "[打倒时间]";
                case PreviewStringId.PageInfo_PageUserName: return "[用户名]";
                case PreviewStringId.PreviewForm_Caption: return " 预览 ";
                case PreviewStringId.SaveDlg_FilterBmp: return "BMP 格式";
                case PreviewStringId.SaveDlg_FilterCsv: return "CSV 文件 ";
                case PreviewStringId.SaveDlg_FilterGif: return "GIF 格式";
                case PreviewStringId.SaveDlg_FilterHtm: return "HTML 文件 ";
                case PreviewStringId.SaveDlg_FilterJpeg: return "JPEG 格式";
                case PreviewStringId.SaveDlg_FilterMht: return "MHT 文件 ";
                case PreviewStringId.SaveDlg_FilterPdf: return "PDF 文件 ";
                case PreviewStringId.SaveDlg_FilterPng: return "PNG 格式";
                case PreviewStringId.SaveDlg_FilterRtf: return "RTF 文件 ";
                case PreviewStringId.SaveDlg_FilterTiff: return "TIFF 格式";
                case PreviewStringId.SaveDlg_FilterTxt: return "TXT 文件 ";
                case PreviewStringId.SaveDlg_FilterWmf: return "WMF 图元";
                case PreviewStringId.SaveDlg_FilterXls: return "Excel 文件 ";
                case PreviewStringId.SaveDlg_Title: return " 另存为 ";
                case PreviewStringId.SB_CurrentPageNo: return " 目前页码 :";
                case PreviewStringId.SB_PageInfo: return "{0}/{1}";
                case PreviewStringId.SB_PageNone: return " 无 ";
                case PreviewStringId.SB_TotalPageNo: return " 总页码 :";
                case PreviewStringId.SB_ZoomFactor: return " 缩放系数 :";
                case PreviewStringId.ScrollingInfo_Page: return " 页 ";
                case PreviewStringId.TB_TTip_Backgr: return " 背景色 ";
                case PreviewStringId.TB_TTip_Close: return " 退出 ";
                case PreviewStringId.TB_TTip_Customize: return " 自定义 ";
                case PreviewStringId.TB_TTip_EditPageHF: return " 页眉页脚 ";
                case PreviewStringId.TB_TTip_Export: return " 导出文件 ";
                case PreviewStringId.TB_TTip_FirstPage: return " 首页 ";
                case PreviewStringId.TB_TTip_HandTool: return " 手掌工具 ";
                case PreviewStringId.TB_TTip_LastPage: return " 尾页 ";
                case PreviewStringId.TB_TTip_Magnifier: return " 放大 / 缩小 ";
                case PreviewStringId.TB_TTip_Map: return " 文档视图 ";
                case PreviewStringId.TB_TTip_MultiplePages: return " 多页 ";
                case PreviewStringId.TB_TTip_NextPage: return " 下一页 ";
                case PreviewStringId.TB_TTip_PageSetup: return " 页面设置 ";
                case PreviewStringId.TB_TTip_PreviousPage: return " 上一页 ";
                case PreviewStringId.TB_TTip_Print: return " 打印 ";
                case PreviewStringId.TB_TTip_PrintDirect: return " 直接打印 ";
                case PreviewStringId.TB_TTip_Search: return " 搜索 ";
                case PreviewStringId.TB_TTip_Send: return " 发送 E-Mail ";
                case PreviewStringId.TB_TTip_Watermark: return " 水印 ";
                case PreviewStringId.TB_TTip_Zoom: return " 缩放 ";
                case PreviewStringId.TB_TTip_ZoomIn: return " 放大 ";
                case PreviewStringId.TB_TTip_ZoomOut: return " 缩小 ";
                case PreviewStringId.WMForm_Direction_BackwardDiagonal: return " 反向倾斜 ";
                case PreviewStringId.WMForm_Direction_ForwardDiagonal: return " 正向倾斜 ";
                case PreviewStringId.WMForm_Direction_Horizontal: return " 横向 ";
                case PreviewStringId.WMForm_Direction_Vertical: return " 纵向 ";
                case PreviewStringId.WMForm_HorzAlign_Center: return " 置中 ";
                case PreviewStringId.WMForm_HorzAlign_Left: return " 靠左 ";
                case PreviewStringId.WMForm_HorzAlign_Right: return " 靠右 ";
                case PreviewStringId.WMForm_ImageClip: return " 剪辑 ";
                case PreviewStringId.WMForm_ImageStretch: return " 伸展 ";
                case PreviewStringId.WMForm_ImageZoom: return " 缩放 ";
                case PreviewStringId.WMForm_PageRangeRgrItem_All: return " 全部 ";
                case PreviewStringId.WMForm_PageRangeRgrItem_Pages: return " 页码 ";
                case PreviewStringId.WMForm_PictureDlg_Title: return " 选择图片 ";
                case PreviewStringId.WMForm_VertAlign_Bottom: return " 底端 ";
                case PreviewStringId.WMForm_VertAlign_Middle: return " 中间 ";
                case PreviewStringId.WMForm_VertAlign_Top: return " 顶端 ";
                case PreviewStringId.WMForm_Watermark_Asap: return "快速";
                case PreviewStringId.WMForm_Watermark_Confidential: return "保密";
                case PreviewStringId.WMForm_Watermark_Copy: return "复制";
                case PreviewStringId.WMForm_Watermark_DoNotCopy: return "不复制";
                case PreviewStringId.WMForm_Watermark_Draft: return "草图";
                case PreviewStringId.WMForm_Watermark_Evaluation: return "评价";
                case PreviewStringId.WMForm_Watermark_Original: return "原始";
                case PreviewStringId.WMForm_Watermark_Personal: return "个人";
                case PreviewStringId.WMForm_Watermark_Sample: return "样例";
                case PreviewStringId.WMForm_Watermark_TopSecret: return "绝密";
                case PreviewStringId.WMForm_Watermark_Urgent: return "紧急";
                case PreviewStringId.WMForm_ZOrderRgrItem_Behind: return " 在后面 ";
                case PreviewStringId.WMForm_ZOrderRgrItem_InFront: return " 在前面 ";
                case PreviewStringId.TB_TTip_Parameters: return " 参数 ";
                case PreviewStringId.BarText_Toolbar: return " 工具栏 ";
                case PreviewStringId.BarText_StatusBar: return " 状态栏 ";
                case PreviewStringId.BarText_MainMenu: return " 主菜单 ";
                case PreviewStringId.SB_TTip_Stop: return " 停止 ";
                case PreviewStringId.RibbonPreview_Open_Caption: return " 打开 ";
                case PreviewStringId.TB_TTip_Open: return " 打开文件 ";
                case PreviewStringId.RibbonPreview_Save_Caption: return " 保存 ";
                case PreviewStringId.TB_TTip_Save: return " 保存文件 ";
                case PreviewStringId.TB_TTip_Scale: return " 缩放 ";
                case PreviewStringId.MenuItem_PageLayout: return " &页面布局 ";
                case PreviewStringId.MenuItem_ViewFacing: return " &覆盖 ";
                case PreviewStringId.MenuItem_ViewContinuous: return " &连续的 ";
                case PreviewStringId.MenuItem_XlsxDocument: return " XLSX 文件 ";
                case PreviewStringId.MenuItem_ZoomPageWidth: return " 页宽 ";
                case PreviewStringId.MenuItem_ZoomWholePage: return " 整页 ";
                case PreviewStringId.MenuItem_ZoomTwoPages: return " 双页 ";
                case PreviewStringId.ScalePopup_GroupText: return " 缩放 ";
                case PreviewStringId.ScalePopup_AdjustTo: return " 调整: ";
                case PreviewStringId.ScalePopup_NormalSize: return " % 正常大小 ";
                case PreviewStringId.ScalePopup_FitTo: return " 适应 ";
                case PreviewStringId.ScalePopup_PagesWide: return " 页宽 ";
                case PreviewStringId.OpenFileDialog_Filter: return " 视图文件 (*{0})|*{0}|所有文件 (*.*)|*.* ";
                case PreviewStringId.OpenFileDialog_Title: return " 打开 ";
                case PreviewStringId.SaveDlg_FilterNativeFormat: return " 普通格式 ";
                case PreviewStringId.SB_PageOfPages: return " 页 {0} / {1} ";
                case PreviewStringId.MenuItem_ZoomTextWidth: return " 内容宽度 ";
                case PreviewStringId.ExportOption_PdfPageRange: return " 页范围: ";
                case PreviewStringId.ExportOption_PdfNeverEmbeddedFonts: return " 排除这些字体: ";
                case PreviewStringId.ExportOption_PdfConvertImagesToJpeg: return " 转换为JPEG格式 ";
                case PreviewStringId.ExportOption_PdfImageQuality: return " 图像质量: ";
                case PreviewStringId.ExportOption_PdfCompressed: return " 压缩 ";
                case PreviewStringId.ExportOption_PdfShowPrintDialogOnOpen: return " 打开时显示打印窗口 ";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions: return " 安全密码: ";
                case PreviewStringId.ExportOption_PdfDocumentApplication: return " 应用: ";
                case PreviewStringId.ExportOption_PdfDocumentAuthor: return " 作者: ";
                case PreviewStringId.ExportOption_PdfDocumentKeywords: return " 关键字: ";
                case PreviewStringId.ExportOption_PdfDocumentSubject: return " 主题: ";
                case PreviewStringId.ExportOption_PdfDocumentTitle: return " 标题: ";
                case PreviewStringId.ExportOptionsForm_CaptionPdf: return " PDF 导出选项 ";
                case PreviewStringId.ExportOption_PdfImageQuality_Highest: return " 最高 ";
                case PreviewStringId.ExportOption_PdfImageQuality_Lowest: return " 最低 ";
                case PreviewStringId.ExportOption_PdfImageQuality_Low: return " 低 ";
                case PreviewStringId.ExportOption_PdfImageQuality_Medium: return " 介质 ";
                case PreviewStringId.ExportOption_PdfImageQuality_High: return " 高 ";
                case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_None: return " (空) ";
                case PreviewStringId.ExportOption_HtmlExportMode: return " 导出类型: ";
                case PreviewStringId.ExportOption_HtmlPageRange: return " 分页: ";
                case PreviewStringId.ExportOption_HtmlPageBorderColor: return " 页面边框颜色: ";
                case PreviewStringId.ExportOption_HtmlPageBorderWidth: return " 页面边框宽度: ";
                case PreviewStringId.ExportOption_HtmlTitle: return " 标题: ";
                case PreviewStringId.ExportOption_HtmlCharacterSet: return " 字符集: ";
                case PreviewStringId.ExportOption_HtmlRemoveSecondarySymbols: return " 移除回车符 ";
                case PreviewStringId.ExportOption_HtmlEmbedImagesInHTML: return " 在网页中嵌入图片 ";
                case PreviewStringId.ExportOptionsForm_CaptionHtml: return " 网页导出选 ";
                case PreviewStringId.ExportOption_HtmlExportMode_SingleFile: return " 单一文件 ";
                case PreviewStringId.ExportOption_HtmlExportMode_SingleFilePageByPage: return " 具体文件 ";
                case PreviewStringId.ExportOption_HtmlExportMode_DifferentFiles: return " 文件类型 "; ;
                case PreviewStringId.ExportOptionsForm_CaptionMht: return " MHT 导出选项 ";

                case PreviewStringId.ExportOption_RtfExportMode: return " 导出类型: ";
                case PreviewStringId.ExportOption_RtfPageRange: return " 分页: ";
                case PreviewStringId.ExportOption_RtfExportWatermarks: return " 导出水印 ";
                case PreviewStringId.ExportOptionsForm_CaptionRtf: return " RTF 导出选项 ";
                case PreviewStringId.ExportOption_RtfExportMode_SingleFilePageByPage: return " 具体文件 ";
                case PreviewStringId.ExportOption_RtfExportMode_SingleFile: return " 单一文件 ";
                case PreviewStringId.ExportOption_XlsExportMode: return " 导出类型: ";
                case PreviewStringId.ExportOption_XlsPageRange: return " 分页: ";
                case PreviewStringId.ExportOption_XlsSheetName: return " 表名: ";
                case PreviewStringId.ExportOption_TextExportMode: return " 导出文件类型: ";
                case PreviewStringId.ExportOption_XlsShowGridLines: return " 显示表格线 ";
                case PreviewStringId.ExportOption_XlsExportHyperlinks: return " 导出连接 ";
                case PreviewStringId.ExportOptionsForm_CaptionXls: return " XLS 导出选项 ";
                case PreviewStringId.ExportOption_XlsExportMode_SingleFile: return " 单一文件 ";
                case PreviewStringId.ExportOption_XlsExportMode_DifferentFiles: return " 文件类型 ";
                case PreviewStringId.ExportOption_TextExportMode_Value: return " 值";
                case PreviewStringId.ExportOption_TextExportMode_Text: return " 文本 ";
                case PreviewStringId.ExportOption_XlsxExportMode: return " 导出文件类型: ";
                case PreviewStringId.ExportOption_XlsxPageRange: return " 分页: ";
                case PreviewStringId.ExportOptionsForm_CaptionXlsx: return " XLSX 导出选项";
                case PreviewStringId.ExportOption_XlsxExportMode_SingleFile: return " 单一文件 ";
                case PreviewStringId.ExportOption_XlsxExportMode_SingleFilePageByPage: return " 具体文件 ";
                case PreviewStringId.ExportOption_XlsxExportMode_DifferentFiles: return " 文件类型 ";
                case PreviewStringId.ExportOption_TextEncoding: return " 编码: ";
                case PreviewStringId.ExportOption_TextSeparator: return " 文本分隔符: ";
                case PreviewStringId.ExportOption_TextQuoteStringsWithSeparators: return " 引用分隔符 ";
                case PreviewStringId.ExportOptionsForm_CaptionCsv: return " CSV 导出选项 ";
                case PreviewStringId.ExportOptionsForm_CaptionTxt: return " 文本导出选项 ";
                case PreviewStringId.ExportOption_TextSeparator_TabAlias: return " TAB 符 ";
                case PreviewStringId.ExportOption_ImageFormat: return " 图片格式: ";
                case PreviewStringId.ExportOption_ImageResolution: return " 分辨率(dpi): ";
                case PreviewStringId.ExportOption_ImageExportMode: return " 导出类型: ";
                case PreviewStringId.ExportOption_ImagePageRange: return " 分页: ";
                case PreviewStringId.ExportOption_ImagePageBorderColor: return " 边框颜色: ";
                case PreviewStringId.ExportOption_ImagePageBorderWidth: return " 边框宽度: ";
                case PreviewStringId.ExportOptionsForm_CaptionImage: return " 图片导出选项 ";
                case PreviewStringId.ExportOption_ImageExportMode_SingleFile: return " 单一文件 ";
                case PreviewStringId.ExportOption_ImageExportMode_SingleFilePageByPage: return " 指定文件 ";
                case PreviewStringId.ExportOption_ImageExportMode_DifferentFiles: return " 文件类型 ";

                #endregion
            }

            var value = base.GetLocalizedString(id);
            File.AppendAllText(@"D:\PreviewLocalizer.txt",
                string.Format("case PreviewStringId.{0}: return @\" {1} \";\r\n", id, value));

            return base.GetLocalizedString(id);
        }
    }
}
